### PR TITLE
Fix build with make-4.4.

### PR DESCRIPTION
**Pull request by valandil**
make-4.4 changed the behaviour of .SECONDEXPANSION to only expand rules that were explicitly used by the currently built target. Because leveldata used .SECONDEXPANSION to override an implicit pattern rule with another implicit pattern rule, the override wasn't considered for expansion and never used. By replacing the implicit pattern override with a static pattern override, i.e. by explicitly listing the dependencies, the rule takes precedence over the implicit pattern rule ($(BUILD_DIR)/*.elf) and gets expanded.

This patch fixes the build for make-4.4, and was also tested with make-4.3.

### CODE REVIEW

**Review by Sonic1paRadise — COMMENTED** [review]
X No default remote repository has been set for this directory.

**Review by mountainflaw — APPROVED** [review]

**Comment by mountainflaw** [comment]
Will be merged in upstream after testing.

**Comment by Sonic1paRadise** [comment]
Nice

**Comment by zZeck** [comment]
I just hit this when building on Gentoo. The fix works great.

**Comment by ghost** [comment]
This PR fixed the `undefined reference to` building errors on Arch Linux.

I highly suggest merging this PR - otherwise people will assume the project is broken and start complaining about it through invalid PRs (since the ability to open an Issue is disabled) or the Discord server (which appears to be dead with barely anyone chatting in it).

Not to mention, this repository hasn't had any activity for 6 months. If this repository is abandoned, I suggest marking it as archive or so.

**Comment by bahamas10** [comment]
This PR fixed the issues as noted in my gist here https://gist.github.com/bahamas10/92b742bd88d3ce106de271454bb5fbd6 on an m1 mac.

**Comment by legluondunet** [comment]
This pr fixed my compilation error on Manjaro 24.0.0 Wynsdey wich uses GNU Make 4.4.1
